"""Generated by gen_derivatives.py from derivatives.yaml. DO NOT EDIT.

Every op exposes two plain functions over np.ndarray:

    <name>_forward(*args)                             -> ndarray
    <name>_backward(grad, result, *args, needs=...)   -> tuple of grads

`needs` is a per-differentiable-arg mask; a False entry yields None instead of
a computed gradient, so an autograd engine can skip work for leaves that do not
require grad. Look up either function by name in FORWARDS / BACKWARDS, and use
SCHEMA to find out what an op takes and what it needs saved for its backward.
"""

import numpy as np

try:
    from .derivative_helpers import (
        cross_entropy_grad_logits,
        cross_entropy_loss,
        gelu_fn,
        gelu_grad,
        layernorm_apply,
        layernorm_grad_input,
        layernorm_xhat,
        log_softmax_stable,
        permute_grad,
        reduced_count,
        scatter_add,
        unbroadcast,
        unreduce,
    )
except ImportError:  # running from inside src/ rather than as a package
    from derivative_helpers import (
        cross_entropy_grad_logits,
        cross_entropy_loss,
        gelu_fn,
        gelu_grad,
        layernorm_apply,
        layernorm_grad_input,
        layernorm_xhat,
        log_softmax_stable,
        permute_grad,
        reduced_count,
        scatter_add,
        unbroadcast,
        unreduce,
    )


def add_forward(self, other):
    """Elementwise addition."""
    return self + other


def add_backward(grad, result, self, other, needs=(True, True)):
    """Gradients of add w.r.t. self, other."""
    grads = [None] * 2
    if needs[0]:
        grads[0] = unbroadcast(grad, np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(grad, np.shape(other))
    return tuple(grads)


def sub_forward(self, other):
    """Elementwise subtraction."""
    return self - other


def sub_backward(grad, result, self, other, needs=(True, True)):
    """Gradients of sub w.r.t. self, other."""
    grads = [None] * 2
    if needs[0]:
        grads[0] = unbroadcast(grad, np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(-grad, np.shape(other))
    return tuple(grads)


def mul_forward(self, other):
    """Elementwise multiplication."""
    return self * other


def mul_backward(grad, result, self, other, needs=(True, True)):
    """Gradients of mul w.r.t. self, other."""
    grads = [None] * 2
    if needs[0]:
        grads[0] = unbroadcast(grad * other, np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(grad * self, np.shape(other))
    return tuple(grads)


def div_forward(self, other):
    """Elementwise division."""
    return self / other


def div_backward(grad, result, self, other, needs=(True, True)):
    """Gradients of div w.r.t. self, other."""
    grads = [None] * 2
    if needs[0]:
        grads[0] = unbroadcast(grad / other, np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(-grad * self / (other * other), np.shape(other))
    return tuple(grads)


def neg_forward(self):
    """Negation."""
    return -self


def neg_backward(grad, result, self, needs=(True,)):
    """Gradients of neg w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(-grad, np.shape(self))
    return tuple(grads)


def pow_forward(self, exponent):
    """Raise to a constant power."""
    return self ** exponent


def pow_backward(grad, result, self, exponent, needs=(True,)):
    """Gradients of pow w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * exponent * self ** (exponent - 1), np.shape(self))
    return tuple(grads)


def exp_forward(self):
    """Elementwise exp."""
    return np.exp(self)


def exp_backward(grad, result, self, needs=(True,)):
    """Gradients of exp w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * result, np.shape(self))
    return tuple(grads)


def log_forward(self):
    """Elementwise natural log."""
    return np.log(self)


def log_backward(grad, result, self, needs=(True,)):
    """Gradients of log w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad / self, np.shape(self))
    return tuple(grads)


def sqrt_forward(self):
    """Elementwise square root."""
    return np.sqrt(self)


def sqrt_backward(grad, result, self, needs=(True,)):
    """Gradients of sqrt w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad / (2.0 * result), np.shape(self))
    return tuple(grads)


def tanh_forward(self):
    """Hyperbolic tangent."""
    return np.tanh(self)


def tanh_backward(grad, result, self, needs=(True,)):
    """Gradients of tanh w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * (1.0 - result * result), np.shape(self))
    return tuple(grads)


def sigmoid_forward(self):
    """Logistic sigmoid."""
    return 1.0 / (1.0 + np.exp(-self))


def sigmoid_backward(grad, result, self, needs=(True,)):
    """Gradients of sigmoid w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * result * (1.0 - result), np.shape(self))
    return tuple(grads)


def relu_forward(self):
    """Rectified linear unit. Subgradient 0 at the kink."""
    return np.maximum(self, 0.0)


def relu_backward(grad, result, self, needs=(True,)):
    """Gradients of relu w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * (self > 0.0), np.shape(self))
    return tuple(grads)


def gelu_forward(self):
    """GELU, tanh approximation (the variant GPT-2 uses)."""
    return gelu_fn(self)


def gelu_backward(grad, result, self, needs=(True,)):
    """Gradients of gelu w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(gelu_grad(grad, self), np.shape(self))
    return tuple(grads)


def matmul_forward(self, other):
    """Matrix product. Both operands must be at least 2-D."""
    return self @ other


def matmul_backward(grad, result, self, other, needs=(True, True)):
    """Gradients of matmul w.r.t. self, other."""
    grads = [None] * 2
    if needs[0]:
        grads[0] = unbroadcast(grad @ np.swapaxes(other, -1, -2), np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(np.swapaxes(self, -1, -2) @ grad, np.shape(other))
    return tuple(grads)


def sum_forward(self, dim=None, keepdim=False):
    """Sum over dim (or everything when dim is None)."""
    return np.sum(self, axis=dim, keepdims=keepdim)


def sum_backward(grad, result, self, dim=None, keepdim=False, needs=(True,)):
    """Gradients of sum w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(unreduce(grad, np.shape(self), dim, keepdim), np.shape(self))
    return tuple(grads)


def mean_forward(self, dim=None, keepdim=False):
    """Mean over dim (or everything when dim is None)."""
    return np.mean(self, axis=dim, keepdims=keepdim)


def mean_backward(grad, result, self, dim=None, keepdim=False, needs=(True,)):
    """Gradients of mean w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(unreduce(grad, np.shape(self), dim, keepdim) / reduced_count(np.shape(self), dim), np.shape(self))
    return tuple(grads)


def max_forward(self, dim=None, keepdim=False):
    """Max over dim. On ties the gradient is copied to every tied element (torch picks one)."""
    return np.max(self, axis=dim, keepdims=keepdim)


def max_backward(grad, result, self, dim=None, keepdim=False, needs=(True,)):
    """Gradients of max w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(unreduce(grad, np.shape(self), dim, keepdim) * (self == unreduce(result, np.shape(self), dim, keepdim)), np.shape(self))
    return tuple(grads)


def reshape_forward(self, shape):
    """Reshape. Pure view bookkeeping, so the backward is just the inverse reshape."""
    return np.reshape(self, shape)


def reshape_backward(grad, result, self, shape, needs=(True,)):
    """Gradients of reshape w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(np.reshape(grad, np.shape(self)), np.shape(self))
    return tuple(grads)


def transpose_forward(self, dim0=-2, dim1=-1):
    """Swap two axes."""
    return np.swapaxes(self, dim0, dim1)


def transpose_backward(grad, result, self, dim0=-2, dim1=-1, needs=(True,)):
    """Gradients of transpose w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(np.swapaxes(grad, dim0, dim1), np.shape(self))
    return tuple(grads)


def permute_forward(self, dims):
    """Arbitrary axis permutation."""
    return np.transpose(self, dims)


def permute_backward(grad, result, self, dims, needs=(True,)):
    """Gradients of permute w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(permute_grad(grad, dims), np.shape(self))
    return tuple(grads)


def embedding_forward(weight, index):
    """Token-embedding lookup. Repeated ids accumulate, hence scatter-add."""
    return weight[index]


def embedding_backward(grad, result, weight, index, needs=(True,)):
    """Gradients of embedding w.r.t. weight."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(scatter_add(np.shape(weight), index, grad, weight.dtype), np.shape(weight))
    return tuple(grads)


def softmax_forward(self, dim=-1):
    """Softmax. Backward uses the output, so no Jacobian is ever materialized."""
    return np.exp(self - np.max(self, axis=dim, keepdims=True)) / np.sum(np.exp(self - np.max(self, axis=dim, keepdims=True)), axis=dim, keepdims=True)


def softmax_backward(grad, result, self, dim=-1, needs=(True,)):
    """Gradients of softmax w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast((grad - np.sum(grad * result, axis=dim, keepdims=True)) * result, np.shape(self))
    return tuple(grads)


def log_softmax_forward(self, dim=-1):
    """Numerically stable log(softmax(x))."""
    return log_softmax_stable(self, dim)


def log_softmax_backward(grad, result, self, dim=-1, needs=(True,)):
    """Gradients of log_softmax w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad - np.exp(result) * np.sum(grad, axis=dim, keepdims=True), np.shape(self))
    return tuple(grads)


def masked_fill_forward(self, mask, value):
    """Fill where mask is True. Used for the causal attention mask."""
    return np.where(mask, value, self)


def masked_fill_backward(grad, result, self, mask, value, needs=(True,)):
    """Gradients of masked_fill w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(grad * np.logical_not(mask), np.shape(self))
    return tuple(grads)


def layernorm_forward(self, weight, bias, eps=1e-05):
    """LayerNorm over the last axis. Fused, so the mean/var graph never materializes."""
    return layernorm_apply(self, weight, bias, eps)


def layernorm_backward(grad, result, self, weight, bias, eps=1e-05, needs=(True, True, True)):
    """Gradients of layernorm w.r.t. self, weight, bias."""
    grads = [None] * 3
    if needs[0]:
        grads[0] = unbroadcast(layernorm_grad_input(grad, self, weight, eps), np.shape(self))
    if needs[1]:
        grads[1] = unbroadcast(grad * layernorm_xhat(self, eps), np.shape(weight))
    if needs[2]:
        grads[2] = unbroadcast(grad, np.shape(bias))
    return tuple(grads)


def cross_entropy_forward(self, target):
    """Mean cross-entropy over flattened positions. `self` is raw logits."""
    return cross_entropy_loss(self, target)


def cross_entropy_backward(grad, result, self, target, needs=(True,)):
    """Gradients of cross_entropy w.r.t. self."""
    grads = [None] * 1
    if needs[0]:
        grads[0] = unbroadcast(cross_entropy_grad_logits(grad, self, target), np.shape(self))
    return tuple(grads)


FORWARDS = {
    "add": add_forward,
    "sub": sub_forward,
    "mul": mul_forward,
    "div": div_forward,
    "neg": neg_forward,
    "pow": pow_forward,
    "exp": exp_forward,
    "log": log_forward,
    "sqrt": sqrt_forward,
    "tanh": tanh_forward,
    "sigmoid": sigmoid_forward,
    "relu": relu_forward,
    "gelu": gelu_forward,
    "matmul": matmul_forward,
    "sum": sum_forward,
    "mean": mean_forward,
    "max": max_forward,
    "reshape": reshape_forward,
    "transpose": transpose_forward,
    "permute": permute_forward,
    "embedding": embedding_forward,
    "softmax": softmax_forward,
    "log_softmax": log_softmax_forward,
    "masked_fill": masked_fill_forward,
    "layernorm": layernorm_forward,
    "cross_entropy": cross_entropy_forward,
}

BACKWARDS = {
    "add": add_backward,
    "sub": sub_backward,
    "mul": mul_backward,
    "div": div_backward,
    "neg": neg_backward,
    "pow": pow_backward,
    "exp": exp_backward,
    "log": log_backward,
    "sqrt": sqrt_backward,
    "tanh": tanh_backward,
    "sigmoid": sigmoid_backward,
    "relu": relu_backward,
    "gelu": gelu_backward,
    "matmul": matmul_backward,
    "sum": sum_backward,
    "mean": mean_backward,
    "max": max_backward,
    "reshape": reshape_backward,
    "transpose": transpose_backward,
    "permute": permute_backward,
    "embedding": embedding_backward,
    "softmax": softmax_backward,
    "log_softmax": log_softmax_backward,
    "masked_fill": masked_fill_backward,
    "layernorm": layernorm_backward,
    "cross_entropy": cross_entropy_backward,
}

SCHEMA = {
    "add": {
        "args": ('self', 'other'),
        "differentiable": ('self', 'other'),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": (),
        "doc": 'Elementwise addition.',
    },
    "sub": {
        "args": ('self', 'other'),
        "differentiable": ('self', 'other'),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": (),
        "doc": 'Elementwise subtraction.',
    },
    "mul": {
        "args": ('self', 'other'),
        "differentiable": ('self', 'other'),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self', 'other'),
        "doc": 'Elementwise multiplication.',
    },
    "div": {
        "args": ('self', 'other'),
        "differentiable": ('self', 'other'),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self', 'other'),
        "doc": 'Elementwise division.',
    },
    "neg": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": (),
        "doc": 'Negation.',
    },
    "pow": {
        "args": ('self', 'exponent'),
        "differentiable": ('self',),
        "nondiff": ('exponent',),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self', 'exponent'),
        "doc": 'Raise to a constant power.',
    },
    "exp": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": True,
        "saves_inputs": (),
        "doc": 'Elementwise exp.',
    },
    "log": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self',),
        "doc": 'Elementwise natural log.',
    },
    "sqrt": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": True,
        "saves_inputs": (),
        "doc": 'Elementwise square root.',
    },
    "tanh": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": True,
        "saves_inputs": (),
        "doc": 'Hyperbolic tangent.',
    },
    "sigmoid": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": True,
        "saves_inputs": (),
        "doc": 'Logistic sigmoid.',
    },
    "relu": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self',),
        "doc": 'Rectified linear unit. Subgradient 0 at the kink.',
    },
    "gelu": {
        "args": ('self',),
        "differentiable": ('self',),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self',),
        "doc": 'GELU, tanh approximation (the variant GPT-2 uses).',
    },
    "matmul": {
        "args": ('self', 'other'),
        "differentiable": ('self', 'other'),
        "nondiff": (),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self', 'other'),
        "doc": 'Matrix product. Both operands must be at least 2-D.',
    },
    "sum": {
        "args": ('self', 'dim', 'keepdim'),
        "differentiable": ('self',),
        "nondiff": ('dim', 'keepdim'),
        "defaults": {'dim': None, 'keepdim': False},
        "saves_result": False,
        "saves_inputs": ('self', 'dim', 'keepdim'),
        "doc": 'Sum over dim (or everything when dim is None).',
    },
    "mean": {
        "args": ('self', 'dim', 'keepdim'),
        "differentiable": ('self',),
        "nondiff": ('dim', 'keepdim'),
        "defaults": {'dim': None, 'keepdim': False},
        "saves_result": False,
        "saves_inputs": ('self', 'dim', 'keepdim'),
        "doc": 'Mean over dim (or everything when dim is None).',
    },
    "max": {
        "args": ('self', 'dim', 'keepdim'),
        "differentiable": ('self',),
        "nondiff": ('dim', 'keepdim'),
        "defaults": {'dim': None, 'keepdim': False},
        "saves_result": True,
        "saves_inputs": ('self', 'dim', 'keepdim'),
        "doc": 'Max over dim. On ties the gradient is copied to every tied element (torch picks one).',
    },
    "reshape": {
        "args": ('self', 'shape'),
        "differentiable": ('self',),
        "nondiff": ('shape',),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self',),
        "doc": 'Reshape. Pure view bookkeeping, so the backward is just the inverse reshape.',
    },
    "transpose": {
        "args": ('self', 'dim0', 'dim1'),
        "differentiable": ('self',),
        "nondiff": ('dim0', 'dim1'),
        "defaults": {'dim0': -2, 'dim1': -1},
        "saves_result": False,
        "saves_inputs": ('dim0', 'dim1'),
        "doc": 'Swap two axes.',
    },
    "permute": {
        "args": ('self', 'dims'),
        "differentiable": ('self',),
        "nondiff": ('dims',),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('dims',),
        "doc": 'Arbitrary axis permutation.',
    },
    "embedding": {
        "args": ('weight', 'index'),
        "differentiable": ('weight',),
        "nondiff": ('index',),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('weight', 'index'),
        "doc": 'Token-embedding lookup. Repeated ids accumulate, hence scatter-add.',
    },
    "softmax": {
        "args": ('self', 'dim'),
        "differentiable": ('self',),
        "nondiff": ('dim',),
        "defaults": {'dim': -1},
        "saves_result": True,
        "saves_inputs": ('dim',),
        "doc": 'Softmax. Backward uses the output, so no Jacobian is ever materialized.',
    },
    "log_softmax": {
        "args": ('self', 'dim'),
        "differentiable": ('self',),
        "nondiff": ('dim',),
        "defaults": {'dim': -1},
        "saves_result": True,
        "saves_inputs": ('dim',),
        "doc": 'Numerically stable log(softmax(x)).',
    },
    "masked_fill": {
        "args": ('self', 'mask', 'value'),
        "differentiable": ('self',),
        "nondiff": ('mask', 'value'),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('mask',),
        "doc": 'Fill where mask is True. Used for the causal attention mask.',
    },
    "layernorm": {
        "args": ('self', 'weight', 'bias', 'eps'),
        "differentiable": ('self', 'weight', 'bias'),
        "nondiff": ('eps',),
        "defaults": {'eps': 1e-05},
        "saves_result": False,
        "saves_inputs": ('self', 'weight', 'eps'),
        "doc": 'LayerNorm over the last axis. Fused, so the mean/var graph never materializes.',
    },
    "cross_entropy": {
        "args": ('self', 'target'),
        "differentiable": ('self',),
        "nondiff": ('target',),
        "defaults": {},
        "saves_result": False,
        "saves_inputs": ('self', 'target'),
        "doc": 'Mean cross-entropy over flattened positions. `self` is raw logits.',
    },
}

__all__ = ["FORWARDS", "BACKWARDS", "SCHEMA"] + [
    f"{n}_{kind}" for n in FORWARDS for kind in ("forward", "backward")
]