"""Codegen: derivatives.yaml -> _derivatives_generated.py.

Mirrors what PyTorch does at build time with tools/autograd: the derivative
formulas are written once, declaratively, and all the boilerplate around them
(signatures, broadcasting fixups, which inputs to save, the dispatch tables) is
generated.

    python src/gen_derivatives.py

Re-run after every edit to derivatives.yaml. Never edit the generated file.
"""

import ast
import builtins
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
SPEC = HERE / "derivatives.yaml"
OUT = HERE / "_derivatives_generated.py"

HEADER = '''"""Generated by gen_derivatives.py from derivatives.yaml. DO NOT EDIT.

Every op exposes two plain functions over np.ndarray:

    <name>_forward(*args)                             -> ndarray
    <name>_backward(grad, result, *args, needs=...)   -> tuple of grads

`needs` is a per-differentiable-arg mask; a False entry yields None instead of
a computed gradient, so an autograd engine can skip work for leaves that do not
require grad. Look up either function by name in FORWARDS / BACKWARDS, and use
SCHEMA to find out what an op takes and what it needs saved for its backward.
"""

import numpy as np

try:
    from .derivative_helpers import {helpers}
except ImportError:  # running from inside src/ rather than as a package
    from derivative_helpers import {helpers}

'''


def identifiers(expr):
    """Bare names an expression reads.

    AST-based rather than regex, so attribute access (np.shape) and keyword
    argument names (axis=) do not count as names the formula depends on.
    """
    tree = ast.parse(expr, mode="eval")
    return {n.id for n in ast.walk(tree) if isinstance(n, ast.Name)}


def render_signature(args, defaults):
    parts = []
    seen_default = False
    for a in args:
        if a in defaults:
            parts.append(f"{a}={defaults[a]!r}")
            seen_default = True
        else:
            if seen_default:
                raise ValueError(
                    f"arg {a!r} has no default but follows one; reorder `args`"
                )
            parts.append(a)
    return parts


def emit_op(op, helper_names):
    name = op["name"]
    args = list(op["args"])
    nondiff = set(op.get("nondiff", []))
    defaults = op.get("defaults", {}) or {}
    derivs = op["derivatives"]
    doc = op.get("doc", "").strip()

    unknown = nondiff - set(args)
    if unknown:
        raise ValueError(f"{name}: nondiff names not in args: {sorted(unknown)}")
    diff_args = [a for a in args if a not in nondiff]
    if set(derivs) != set(diff_args):
        raise ValueError(
            f"{name}: derivatives {sorted(derivs)} do not match "
            f"differentiable args {diff_args}"
        )

    for expr in [op["forward"], *derivs.values()]:
        compile(expr, f"<{name}>", "eval")  # fail at gen time, not import time

    sig = render_signature(args, defaults)
    lines = []

    lines.append(f"def {name}_forward({', '.join(sig)}):")
    lines.append(f'    """{doc}"""' if doc else '    """"""')
    lines.append(f"    return {op['forward']}")
    lines.append("")
    lines.append("")

    needs_default = ", ".join(["True"] * len(diff_args))
    if len(diff_args) == 1:
        needs_default += ","
    bsig = ["grad", "result", *sig, f"needs=({needs_default})"]
    lines.append(f"def {name}_backward({', '.join(bsig)}):")
    lines.append(f'    """Gradients of {name} w.r.t. {", ".join(diff_args)}."""')
    lines.append(f"    grads = [None] * {len(diff_args)}")
    for i, a in enumerate(diff_args):
        lines.append(f"    if needs[{i}]:")
        lines.append(f"        grads[{i}] = unbroadcast({derivs[a]}, np.shape({a}))")
    lines.append("    return tuple(grads)")
    lines.append("")
    lines.append("")

    used = set()
    for expr in derivs.values():
        used |= identifiers(expr)
    saves_result = "result" in used
    saves_inputs = tuple(a for a in args if a in used)
    # helpers can be called from the forward expression too
    used_anywhere = used | identifiers(op["forward"])

    schema = {
        "args": tuple(args),
        "differentiable": tuple(diff_args),
        "nondiff": tuple(a for a in args if a in nondiff),
        "defaults": defaults,
        "saves_result": saves_result,
        "saves_inputs": saves_inputs,
        "doc": doc,
    }
    helper_names |= used_anywhere
    return "\n".join(lines), schema, used_anywhere, args


def main():
    ops = yaml.safe_load(SPEC.read_text())
    names = [op["name"] for op in ops]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise ValueError(f"duplicate op names: {sorted(dupes)}")

    import derivative_helpers

    available = set(derivative_helpers.__all__)
    referenced = set()

    always_known = set(dir(builtins)) | {"np", "grad", "result"}

    # A helper named <op>_forward/<op>_backward would be shadowed by the
    # function generated for that op, turning its call site into recursion.
    collisions = available & {f"{n}_{k}" for n in names for k in ("forward", "backward")}
    if collisions:
        raise ValueError(
            f"helper name(s) {sorted(collisions)} collide with generated "
            f"functions; rename them in derivative_helpers.py"
        )

    bodies, schemas = [], {}
    for op in ops:
        body, schema, used, args = emit_op(op, referenced)
        unknown = used - available - always_known - set(args)
        if unknown:
            raise ValueError(
                f"{op['name']}: formula uses undefined name(s) {sorted(unknown)} -- "
                f"add them to derivative_helpers.__all__"
            )
        bodies.append(body)
        schemas[op["name"]] = schema

    used_helpers = sorted((referenced & available) | {"unbroadcast"})
    helpers_import = "(\n        " + ",\n        ".join(used_helpers) + ",\n    )"

    out = [HEADER.format(helpers=helpers_import)]
    out.extend(bodies)

    out.append("FORWARDS = {")
    for n in names:
        out.append(f'    "{n}": {n}_forward,')
    out.append("}")
    out.append("")
    out.append("BACKWARDS = {")
    for n in names:
        out.append(f'    "{n}": {n}_backward,')
    out.append("}")
    out.append("")
    out.append("SCHEMA = {")
    for n in names:
        s = schemas[n]
        out.append(f'    "{n}": {{')
        for k, v in s.items():
            out.append(f'        "{k}": {v!r},')
        out.append("    },")
    out.append("}")
    out.append("")
    out.append("__all__ = [\"FORWARDS\", \"BACKWARDS\", \"SCHEMA\"] + [")
    out.append("    f\"{n}_{kind}\" for n in FORWARDS for kind in (\"forward\", \"backward\")")
    out.append("]")
    out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT.relative_to(HERE.parent)} ({len(ops)} ops)")


if __name__ == "__main__":
    main()
